# The production environment runs the live application on the production server. Debugging outputs are minimized and
# the application runs with stricter configurations.
services:
  api1:
    image: ${APPLICATION_API_IMAGE}
    environment:
      - NODE_ENV=production

  api2:
    image: ${APPLICATION_API_IMAGE}
    environment:
      - NODE_ENV=production

  jobs:
    image: ${APPLICATION_JOBS_IMAGE}

  # add logging in production environment
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: rcb-discord-bot-otel-collector
    environment:
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      HONEYCOMB_DATASET: ${HONEYCOMB_DATASET}
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml:ro
    command: ["--config", "/etc/otel/config.yaml"]
    ports:
      - "4317:4317"
    networks:
      - core-network