# The production environment runs the live application on the production server. Debugging outputs are minimized and
# the application runs with stricter configurations.
services:
  api1:
    image: {APPLICATION_API_IMAGE}
    build:
      dockerfile: ./docker/api/Dockerfile
    environment:
      - NODE_ENV=production

  api2:
    image: {APPLICATION_API_IMAGE}
    build:
      dockerfile: ./docker/api/Dockerfile
    environment:
      - NODE_ENV=production

  jobs:
    image: {APPLICATION_JOBS_IMAGE}
    build:
      dockerfile: ./docker/jobs/Dockerfile