# The development environment runs the live application on the development server.
services:
  api1:
    image: {APPLICATION_API_IMAGE}
    build:
      dockerfile: ./docker/api/Dockerfile
    environment:
      - NODE_ENV=development

  api2:
    image: {APPLICATION_API_IMAGE}
    build:
      dockerfile: ./docker/api/Dockerfile
    environment:
      - NODE_ENV=development

  jobs:
    image: {APPLICATION_JOBS_IMAGE}
    build:
      dockerfile: ./docker/jobs/Dockerfile