# These are local overrides for developers to run locally when developing.
services:
  api1:
    # for hot reloading in local dev
    command: npm run start:watch-api
    # codebase mounted for local dev
    volumes:
      - ..:/app
      - /app/node_modules

  api2:
    # for hot reloading in local dev
    command: npm run start:watch-api
    # codebase mounted for local dev
    volumes:
      - ..:/app
      - /app/node_modules

  jobs:
    # for hot reloading in local dev
    command: npm run start:watch-jobs
    # codebase mounted for local dev
    volumes:
      - ..:/app
      - /app/node_modules