# The development environment runs the live application on the development server.
services:
  api1:
    build:
      dockerfile: ./docker/api/Dockerfile
    env_file:
      - ../config/env/.env.development
    environment:
      - NODE_ENV=development

  api2:
    build:
      dockerfile: ./docker/api/Dockerfile
    env_file:
      - ../config/env/.env.development
    environment:
      - NODE_ENV=development

  jobs:
    build:
      dockerfile: ./docker/jobs/Dockerfile
    env_file:
      - ../config/env/.env.development

  redis-sessions:
    env_file:
      - ../config/env/.env.development

  redis-ephemeral:
    env_file:
      - ../config/env/.env.development

  mysql:
    env_file:
      - ../config/env/.env.development

  minio:
    env_file:
      - ../config/env/.env.development